import mongoose from 'mongoose';

/**
 * UMICO Product model
 *
 * Supports a flexible variant system:
 *  - hasVariants = false → single SKU, use top-level price/stock/sku
 *  - hasVariants = true  → use `variants[]`, each with its own
 *                          dimensionValues (e.g. { size: "50ml",
 *                          countryVariant: "Korean Version" }),
 *                          price, stock, sku, images, etc.
 *
 * `variantDimensions` lists which dimensions this product actually uses
 * (e.g. ["size"], ["countryVariant"], ["size", "countryVariant"]).
 */

const ProductImageSchema = new mongoose.Schema(
  {
    url: { type: String, required: true }, // local upload path
    alt: { type: String, default: '' },
    sortOrder: { type: Number, default: 0 },
    // Multi-size variants generated by sharp on upload
    thumbnail: { type: String, default: '' },
    medium: { type: String, default: '' },
    large: { type: String, default: '' },
  },
  { _id: false }
);

const VariantSchema = new mongoose.Schema(
  {
    // e.g. { size: "50ml", countryVariant: "Korean Version" }
    dimensionValues: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
    sku: { type: String, default: '', index: true },
    barcode: { type: String, default: '' },
    price: { type: Number, required: true, min: 0 },
    compareAtPrice: { type: Number, default: 0, min: 0 },
    stock: { type: Number, default: 0, min: 0 },
    lowStockThreshold: { type: Number, default: 5 },
    weight: { type: Number, default: 0 }, // grams
    images: { type: [ProductImageSchema], default: [] }, // optional override
    status: {
      type: String,
      enum: ['active', 'inactive'],
      default: 'active',
    },
  },
  { _id: true }
);

const ProductSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    slug: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      index: true,
    },

    brand: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Brand',
      required: true,
      index: true,
    },
    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Category',
      required: true,
      index: true,
    },
    subcategory: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Category',
      default: null,
    },

    // Content
    description: { type: String, default: '' }, // rich text (HTML)
    ingredients: { type: String, default: '' },
    howToUse: { type: String, default: '' },

    suitability: {
      type: String,
      enum: ['everyone', 'primarily_women', 'primarily_men', 'unisex'],
      default: 'everyone',
      index: true,
    },

    mainImages: { type: [ProductImageSchema], default: [] },

    // SEO
    seoTitle: { type: String, default: '' },
    seoDescription: { type: String, default: '' },
    seoKeywords: { type: [String], default: [] },

    status: {
      type: String,
      enum: ['active', 'inactive', 'draft'],
      default: 'draft',
      index: true,
    },

    isFeatured: { type: Boolean, default: false, index: true },
    isNewArrival: { type: Boolean, default: false, index: true },
    isBestSeller: { type: Boolean, default: false, index: true },

    // Variant system
    hasVariants: { type: Boolean, default: false },
    variantDimensions: { type: [String], default: [] }, // e.g. ['size', 'countryVariant']
    variants: { type: [VariantSchema], default: [] },

    // Used only when hasVariants = false
    sku: { type: String, default: '' },
    barcode: { type: String, default: '' },
    price: { type: Number, default: 0, min: 0 },
    compareAtPrice: { type: Number, default: 0, min: 0 },
    stock: { type: Number, default: 0, min: 0 },
    lowStockThreshold: { type: Number, default: 5 },
    weight: { type: Number, default: 0 },

    tags: { type: [String], default: [] },

    // Analytics counters
    viewCount: { type: Number, default: 0 },
    salesCount: { type: Number, default: 0 },
    wishlistCount: { type: Number, default: 0 },
    averageRating: { type: Number, default: 0 },
    reviewCount: { type: Number, default: 0 },
  },
  { timestamps: true }
);

ProductSchema.index({ name: 'text', tags: 'text' });
ProductSchema.index({ status: 1, isFeatured: 1 });
ProductSchema.index({ status: 1, isNewArrival: 1 });
ProductSchema.index({ status: 1, isBestSeller: 1 });
ProductSchema.index({ brand: 1, status: 1 });
ProductSchema.index({ category: 1, status: 1 });
ProductSchema.index({ createdAt: -1 });

export default mongoose.models.Product || mongoose.model('Product', ProductSchema);
